#custom:
message: updated @12:04


person:
  greeting: Hello,
  farewell: Goodbye,

#management:
#  security:
#    enabled: false

security:
#  user:
#    password: password
  oauth2:
    client:
      client-id: 70a9c16f-238c-47a2-8e3f-276e29b311dc
      client-secret: cfd6d83b-f3d9-4d73-aad9-bfe74ce8afc2
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token

server:
  port: 8081

spring:
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/testdb?useSSL=false
  username: springboot
  password: workshop

queue_name: spring-mq-sample

endpoint:
  beans:
    sensitive: true
  shutdown:
    enabled: true
  id: mappings

# Directory Service
directory:
  url: http://directory-service-v1-circumfluent-pneumatology.apps.cumuluslabs.io/directories/${company.id}

# Company
company.id: 4